export declare const TIMEOUT = 100000;

export const transformator = {
    prevoz_0: 'Kupac preuzima robu',
    prevoz_1: 'Automaterijal vozi robu',
    prevoz_2: 'Treće lice vozi robu',
    kategorija_AMORTIZER: 'Amortizeri',
    kategorija_BRAVA: 'Brava vrata i elek. uložak brave',
    kategorija_BREGASTA: 'Bregasta osovina',
    kategorija_BRISAC: 'Brisači - metlice',
    kategorija_CILINDAR: 'Cilindri-kočioni',
    kategorija_DIHTUNG: 'Dihtunzi',
    kategorija_DISK_PLOCICE: 'Disk pločice',
    kategorija_DISKOVI: 'Diskovi',
    kategorija_DVOTAKTOL: 'Dvotaktol ulje',
    kategorija_GREJAC: 'Grejači',
    kategorija_GUMICE: 'Gumice',
    kategorija_HEMIJA: 'Hemija za automobile',
    kategorija_HIDROPODIZAC: 'Hidropodizači ventila',
    kategorija_HLADNJAK: 'Hladnjak',
    kategorija_ZGLOB: 'Zglob homokinetički',
    kategorija_INTERKULER: 'Interkuler',
    kategorija_KABLOVI: 'Kablovi za svećice',
    kategorija_KARIKE: 'Karike',
    kategorija_KARTER: 'Karter',
    kategorija_KLACKALICA: 'Klackalica',
    kategorija_KVACILO: 'Kvačilo - Zamajci',
    kategorija_KLIP: 'Klip',
    kategorija_KOZMETIKA: 'Kozmetika',
    kategorija_KUGLA: 'Kugla',
    kategorija_LANAC: 'Lanac - klizači, setovi',
    kategorija_LETVA: 'Letva volana - spone',
    kategorija_LEZAJEVI: 'Ležajevi radilice',
    kategorija_MANZENTA: 'Manžetne',
    kategorija_PAKNOVI: 'Paknovi',
    kategorija_PREKIDAC: 'Prekidači',
    kategorija_PROTOKOMER: 'Protokomer',
    kategorija_PUMPA: 'Pumpa za vodu',
    kategorija_RAME: 'Rame',
    kategorija_RAZVODNIK: 'Razvodnik paljenja',
    kategorija_REMENICA: 'Remenice',
    kategorija_SEMERING: 'Semering',
    kategorija_SVECICA: 'Svećice i kablovi',
    kategorija_SIJALICA: 'Sijalice',
    kategorija_SILEN: 'Silen blokovi',
    kategorija_STABILIZATOR: 'Stabilizator',
    kategorija_TERMODAVAC: 'Termodavač',
    kategorija_TERMOSTAT: 'Termostat',
    kategorija_VENTIL: 'Ventili',
    kategorija_VENTILATOR: 'Ventilator',
    kategorija_ZUPCANIK: 'Zupčanici',
    empty: 'N/A'
};

export const mesec = {
    mesec_01: 'Januar',
    mesec_02: 'Februar',
    mesec_03: 'Mart',
    mesec_04: 'April',
    mesec_05: 'Maj',
    mesec_06: 'Jun',
    mesec_07: 'Jul',
    mesec_08: 'Avgust',
    mesec_09: 'Septembar',
    mesec_10: 'Oktobar',
    mesec_11: 'Novembar',
    mesec_12: 'Decembar'
};
